### ISSUE TITLE
Problem with with parameters passed by reference in PHP

### ISSUE THREAD

**Issue by travisrisner** [jeremyvii/vs-docblockr#15]
**Describe the bug**
Extension fails when working with a php function that has a parameter passed by reference.

**To Reproduce**
1. Create a new php file
2. Create a function with a parameter passed by reference(e.g. `&$var`)
3. Try to autocomplete docblock

**Expected behavior**
Extensions should parse and create docblock with the parameter information.

**Code Snippet**
`<?php function foo(string &$bar) {}`

**Enviroment (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Version 0.4.3
 - Language(s) PHP

**Comment by jeremyvii** [comment]
This should be fixed with release [0.4.4](https://github.com/jeremyvii/vs-docblockr/releases/tag/0.4.4)

**Comment by jeremyvii** [comment]
Appears I published the previous patch before pulling down the latest changes on the master branch. Should work with release [0.4.5](https://github.com/jeremyvii/vs-docblockr/releases/tag/0.4.5).
