### ISSUE TITLE
File extensions configuration

### ISSUE THREAD

**Issue by neuronetio** [jeremyvii/vs-docblockr#18]
Could you provide some settings to specify which file type will have comment blocks?
For example I'm using Vue components. This components are files with combination of JS, html, and css with `.vue` extension.
I need to have docblockr snippets inside JS part of code.
Sometimes file names and extension are different than `.js` or `.php` but contain valid js/php code.
It will be usefull to customize file extensions and suitable comment blocks.

Thanks for this plugin anyway!

**Comment by neuronetio** [comment]
If I remember vs-docblock was working inside vue files few days ago... 
I've opened developer tools and saw some bugs in docblocker so this issue is no longer the case.

**Comment by jeremyvii** [comment]
This will probably take some thinking on my part. The extension, at the present, works differently per language. For example, if you are a PHP file with HTML and JavaScript, the extension loads the PHP parser as the current language ID is PHP. Regarding Vue, it may be possible to set up the Vue language ID to load in the JavaScript parser. Once again, I will have to think about this. I will leave this issue open for now.

**Comment by jcontonio** [comment]
Some settings would be nice as I want to use the same `/**` shortcuts in css, sass files as well

**Comment by jeremyvii** [comment]
@jcontonio if you create a new issue with the feature request template, I can look into getting `css` and `sass` implemented.

**Comment by jeremyvii** [comment]
Closed for not using the repository's [feature template](https://github.com/jeremyvii/vs-docblockr/blob/master/.github/ISSUE_TEMPLATE/feature_request.md).
