### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by neuronetio** [jeremyvii/vs-docblockr#19]
![image](https://user-images.githubusercontent.com/25027696/50974137-d16d1300-14ea-11e9-8fc0-fb67ef4553a2.png)

**Comment by jeremyvii** [comment]
Could you provide some more information, such as the steps taken to recreate this issue? It would be helpful if you used the [Bug Report Template](https://github.com/jeremyvii/vs-docblockr/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
