### ISSUE TITLE
Problem with variables that contain "s_" in PHP

### ISSUE THREAD

**Issue by travisrisner** [jeremyvii/vs-docblockr#25]
**Describe the bug**
When working with a PHP file that contains a variable with "s_" in the name, everything after the "s_" is truncated in the description.

**To Reproduce**
1. Create a new PHP file
2. Create a variable named `$tests_testing`
3. Autocomplete the docblock
4. You will see that it describes the variable as `[$test description]`

**Expected behavior**
The docblock should describe the variable as `[$tests_testing description]`

**Code Snippet**
`<?php class Testing { private $tests_testing = 'Value'; }`

**Screenshots**
 - OS: Ubuntu 18.04 LTS
 - Version 0.4.11
 - Language(s) PHP

**Additional context**

**Comment by jeremyvii** [comment]
This has been fixed in the release of [0.4.13](https://github.com/jeremyvii/vs-docblockr/releases/tag/0.4.13).
