### ISSUE TITLE
Could you support Arrow function

### ISSUE THREAD

**Issue by zy199226** [jeremyvii/vs-docblockr#29]

**Comment by jeremyvii** [comment]
Could you please edit this issue to conform to the [feature request template](https://github.com/jeremyvii/vs-docblockr/blob/master/.github/ISSUE_TEMPLATE/feature_request.md)? And I will get this implemented.

**Comment by jeremyvii** [comment]
Closed for not using the repository's [feature template](https://github.com/jeremyvii/vs-docblockr/blob/master/.github/ISSUE_TEMPLATE/feature_request.md).
