### ISSUE TITLE
Typescript not showing block

### ISSUE THREAD

**Issue by daneprime8** [jeremyvii/vs-docblockr#33]
Trying `/**` + enter for a typescript file and it just result sin `/** */`. If I change language mode to javascript it works as expected.

**Code Snippet**
```
static returnsTheThing(arr: string[][], str: string): boolean {
  //  ...  
  return true;
}
```

**Enviroment (please complete the following information):**
ubuntu 18.04.2

**Comment by jeremyvii** [comment]
This should be fixed with the release [0.5.5](https://github.com/jeremyvii/vs-docblockr/releases/tag/0.5.5).
