### ISSUE TITLE
PHP - issue with class properties without a default value

### ISSUE THREAD

**Issue by travisrisner** [jeremyvii/vs-docblockr#35]
**Describe the bug**
When attempting to docblock a class property that does not have a value set, the last letter of the variable name is truncated in the description placeholder.

**To Reproduce**
1. Create a PHP file
2. Create a class
3. Create a property inside the class without defining it's value
4. When autocompleting the docblock, the last character of the variable name is dropped in the placeholder.

**Expected behavior**
The placeholder for [$varname description] should display exactly as the variable name is

**Code Snippet**
`class foo {
  protected $varname;
}
`

**Enviroment (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Language(s) [e.g. JavaScript, PHP]

OS: Ubuntu 18.04 LTS
Version 0.5.5
Language(s) PHP

**Comment by jeremyvii** [comment]
Should be fixed with release [0.5.6](https://github.com/jeremyvii/vs-docblockr/releases/tag/0.5.6).
