### ISSUE TITLE
Suggestion : C language

### ISSUE THREAD

**Issue by rivetchip** [jeremyvii/vs-docblockr#43]
**Is your feature request related to a problem? Please describe.**
A suggestion :smile: 

**Describe the solution you'd like**
Adding C/C++  docblocks too. I see there is `a c-language` branch, but never updated since last year.

**Describe alternatives you've considered**
PHP could be maybe used as a base ?

**Comment by jeremyvii** [comment]
I agree this would be a nice enhancement. Hopefully this can get implemented soon. I'd welcome any attempts at getting C implemented if you'd like to take a wack at it!

**Comment by jeremyvii** [comment]
This is added in the release of [0.7.0](https://github.com/jeremyvii/vs-docblockr/releases/tag/0.7.0).

An additional issue will be created for C++.
