### ISSUE TITLE
typing `/**` and pressing enter does duplicate the `/**` tag

### ISSUE THREAD

**Issue by jdeniau** [jeremyvii/vs-docblockr#63]
**Describe the bug**

typing `/**` and pressing enter does duplicate the `/**` tag. See the following video

![dockblockr small](https://user-images.githubusercontent.com/1398469/81292385-cccb5700-906b-11ea-9b9a-93fc961c8aa9.gif)

**To Reproduce**

1. Go on top of a function
2. Type `/**`
3. Press enter
4. The first line does now contain `/**/**`

**Expected behavior**
Do not duplicate `/**`

**Code Snippet**
If applicable, code snippet you tried to try to apply docblock too

**Screenshots**

**Enviroment (please complete the following information):**
- plugin version : 1.0.1
- Windows 10
- Vscode:
  Version: 1.44.2 (user setup)
  Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
  Date: 2020-04-16T16:36:23.138Z
  Electron: 7.1.11
  Chrome: 78.0.3904.130
  Node.js: 12.8.1
  V8: 7.8.279.23-electron.0
  OS: Windows_NT x64 10.0.18363
- Languages : tested with PHP and Javascript

**Comment by jeremyvii** [comment]
I am having trouble recreating this on my end. Does this happen for you in Typescript as well?

**Comment by jdeniau** [comment]
Yes it does. I tried disabling all other extension, and still the issue 🤔

**Comment by jeremyvii** [comment]
Strange, I am on Ubuntu and it looks like you're on Windows. Could be an OS difference? I can try on a Windows machine later and see if I get the same result.

**Comment by jdeniau** [comment]
Great. I will try on my laptop on Fedora too 👍

**Comment by jeremyvii** [comment]
@jdeniau  I've been having trouble getting my Windows machine to cooperate with me. However, I did find where I could improve how the extension was currently placing the docblock snippets. Would you be willing to test my branch on your machine?

You would need to

- Clone the repository and the switch to the `fix-snippet-range` branch
- Install the `npm` modules
- Click *Launch Extension* under vscode's debugger on the right
- Try a few different languages to see if the snippet is rendering correctly

I can set you as the reviewer on #64 if you are help test this.

**Comment by jdeniau** [comment]
I tried every language and it does work now on my machine 👍

**Comment by jeremyvii** [comment]
Awesome, thanks!
