### ISSUE TITLE
Autocomplete Indentation Broken

### ISSUE THREAD

**Issue by clayliddell** [jeremyvii/vs-docblockr#66]
**Describe the bug**
Whenever creating multi-line comments for some indented piece of code (e.g. a class method, property, or variable declaration) the indentation of the comment is removed during autocomplete.

**Expected behavior**
Whenever creating multi-line comments, the indentation should be preserved for the comment.

**Screenshots**
Expected Behavior:
![Selection_001](https://user-images.githubusercontent.com/9506807/81522720-1dafa980-9311-11ea-82e7-3a40b272abfa.png)
Actual Behavior:
![Selection_002](https://user-images.githubusercontent.com/9506807/81522732-256f4e00-9311-11ea-9e75-1a44e15fe358.png)

**Enviroment (please complete the following information):**
 - OS: Ubuntu
 - Version: 1.1.0
 - Language(s): Tested with PHP, C, and Java

**Additional context**
This appears to have been caused by a [recent commit](https://github.com/jeremyvii/vs-docblockr/commit/adaf438501902b81cf1b89c20a9fc9e6d743d565) (3 days ago) which was added to the recent 1.0.2 release.

**Comment by jeremyvii** [comment]
I noticed this happening when using `/**` + Enter and the `renderFromSelection` command. 
![Peek 2020-05-11 08-11](https://user-images.githubusercontent.com/11360955/81565454-f7185f80-935e-11ea-86c6-0174adf13ddb.gif)
