### ISSUE TITLE
Wrong parameter, miss null

### ISSUE THREAD

**Issue by diosby** [jeremyvii/vs-docblockr#77]
**Describe the bug**
Does not generate parameters with null.

**To Reproduce**
```php 
protected function checkPricingRule(PricingRule $pricingRule = null): ?bool {}
```

**Expected behavior**
```php
    /**
     * [checkPricingRule description]
     *
     * @param   PricingRule|null  $pricingRule  [$pricingRule description]
     *
     * @return  bool|null                       [return description]
     */
    protected function checkPricingRule(PricingRule $pricingRule = null): ?bool
```

**Code**
```php
/**
     * [checkPricingRule description]
     *
     * @param   PricingRule  $pricingRule  [$pricingRule description]
     * @param   null                       [ description]
     *
     * @return  bool                       [return description]
     */
    protected function checkPricingRule(PricingRule $pricingRule = null): ?bool
```

**Screenshots**
![Снимок экрана от 2020-06-04 17-58-41](https://user-images.githubusercontent.com/19969187/83773326-0e601980-a68d-11ea-8262-8584913d7c09.png)

**Enviroment (please complete the following information):**
    OS: Ubuntu 20.04
    VS Code: 1.45.1, the extension: 1.1.2
    Language: PHP

**Comment by jeremyvii** [comment]
The issue where the blank `null` parameter are being rendered will be fixed in the next release. I didn't include rendering a union type based on the parameters default value, as this will take some further thought. Feel free to create an issue using the feature request template for this.
