### ISSUE TITLE
Setting to remove extra blank lines

### ISSUE THREAD

**Issue by John-Dean** [jeremyvii/vs-docblockr#82]
**Is your feature request related to a problem? Please describe.**
Remove the extra blank lines added to the generated DocBlocks.

Current formatting:
```
/**
 * [sample description]
 *
 * @param   {[type]}  param1  [param1 description]
 * @param   {[type]}  param2  [param2 description]
 *
 * @return  {[type]}          [return description]
 */
function sample(param1, param2){}
```

Suggested formatting:
```
/**
 * [sample description]
 * @param   {[type]}  param1  [param1 description]
 * @param   {[type]}  param2  [param2 description]
 * @return  {[type]}          [return description]
 */
function sample(param1, param2){}
```

**Comment by jeremyvii** [comment]
Two settings, **Align Tags** and **New Lines Between Tags**, were adding to give further flexibility with docblock style. These settings will be available in the next release.
