### ISSUE TITLE
Publish to Open-VSX

### ISSUE THREAD

**Issue by TheJaredWilcurt** [jeremyvii/vs-docblockr#88]
VS Chromium uses https://open-vsx.org instead of Microsoft's store. It's basically VSCode but without the spyware built in and runs faster because it has most plugins disabled or not installed by default.

**Comment by jeremyvii** [comment]
Interesting, I wasn't aware they used a separate marketplace. I will look into getting this set up!

**Comment by TheJaredWilcurt** [comment]
looks like it might be as easy as just doing `npx ovsx publish`

**Comment by jeremyvii** [comment]
This extension is using a [GitHub action](https://github.com/jeremyvii/vs-docblockr/blob/main/.github/workflows/publish.yml) to publish to Microsoft's Marketplace. It looks like there is an [action](https://github.com/HaaLeo/publish-vscode-extension) available that will publish to both the Visual Studio Marketplace and the Open VSX Registry. I will need to look at this action more closely when I have time, but I believe it will be the ideal route.

**Comment by jeremyvii** [comment]
After over three years, I have gotten this extension published on the Open VSX Registry. Sorry for the delay. Namespace verification is still depending, as of now. See the link below. 

https://open-vsx.org/extension/jeremyljackson/vs-docblock
https://github.com/EclipseFdn/open-vsx.org/issues/3193
